# Generated by Django 4.2.7 on 2023-12-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0006_device_active_status'),
        ('empgrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupByDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.device')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empgrp.group')),
            ],
        ),
    ]
