# Generated by Django 4.2.7 on 2023-11-12 11:06

from django.db import migrations, models
import django.db.models.deletion
import empfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=empfiles.models.user_file_upload)),
                ('file_description', models.CharField(default='-', max_length=200, null=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
