# Generated by Django 4.2.7 on 2023-11-13 09:38

from django.db import migrations, models
import empfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('empfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=empfiles.models.user_file_upload),
        ),
    ]
