# Generated by Django 4.2.7 on 2023-11-13 09:51

from django.db import migrations, models
import empfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('empfiles', '0002_alter_employeefiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefiles',
            name='file',
            field=models.FileField(default='-', upload_to=empfiles.models.user_file_upload),
            preserve_default=False,
        ),
    ]
