# Generated by Django 4.2.7 on 2023-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(default='-', max_length=100, null=True)),
                ('password', models.CharField(default='-', max_length=100, null=True)),
                ('phone_number', models.CharField(default='-', max_length=100, null=True)),
                ('image_location', models.CharField(max_length=100)),
                ('in_time', models.TimeField(default='08:00:00')),
                ('out_time', models.TimeField(default='17:00:00')),
                ('registration_date', models.DateField(default=None, null=True)),
                ('validity_date', models.CharField(default='user', max_length=100, null=True)),
                ('employee_type', models.CharField(default='user', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
