# Generated by Django 4.2.7 on 2023-11-08 10:26

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_location',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='validity_date',
            field=models.CharField(default=employee.models.get_default_date, max_length=100, null=True),
        ),
    ]
