# Generated by Django 4.2.7 on 2023-11-14 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empgrp', '0001_initial'),
        ('employee', '0005_employee_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empgrp.group'),
        ),
    ]
