# Generated by Django 4.2.7 on 2023-11-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20231114_1538'),
    ]

    operations = [
    ]
