# Generated by Django 4.2.7 on 2023-11-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
    ]
