# Generated by Django 4.2.7 on 2023-11-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20231116_1434'),
    ]

    operations = [
    ]
