# Generated by Django 4.2.7 on 2023-11-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
    ]
