# Generated by Django 4.2.7 on 2023-11-28 07:14

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employee_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cardNo',
            field=models.BigIntegerField(default=employee.models.get_timestamp),
        ),
    ]
