# Generated by Django 4.2.7 on 2023-12-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0003_alter_shiftmanagement_total_time'),
        ('employee', '0019_employee_department_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='out_time',
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.shiftmanagement'),
        ),
    ]
