# Generated by Django 4.2.7 on 2023-12-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0003_alter_shiftmanagement_total_time'),
        ('employee', '0021_alter_employee_shift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.shiftmanagement'),
        ),
    ]
