# Generated by Django 4.2.7 on 2023-12-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('employee', '0025_alter_employee_shift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroupdevice',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices'),
        ),
    ]
