# Generated by Django 4.2.7 on 2023-12-18 11:25

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employeegroupdevice_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainEmployeeFromCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=employee.models.user_file_upload)),
            ],
        ),
    ]
