# Generated by Django 4.2.7 on 2023-12-05 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_employee_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
