# Generated by Django 4.2.7 on 2023-12-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_loginlog_employee_id_alter_loginlog_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loginlog',
            constraint=models.UniqueConstraint(fields=('employee_id', 'username'), name='unique_employee_login'),
        ),
    ]
