# Generated by Django 4.2.7 on 2023-11-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empgrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='-', max_length=100)),
                ('location', models.CharField(default='-', max_length=100, null=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empgrp.group')),
            ],
        ),
    ]
