# Generated by Django 4.2.7 on 2023-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_rename_group_name_device_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
