# Generated by Django 4.2.7 on 2023-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_ip',
            field=models.GenericIPAddressField(protocol='both',unpack_ipv4=True,null=True),
        ),
    ]
