# Generated by Django 4.2.7 on 2023-11-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_device_device_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active_status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
