# Generated by Django 4.2.7 on 2023-11-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_description',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
