# Generated by Django 4.2.7 on 2023-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
