# Generated by Django 4.2.7 on 2023-12-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftmanagement',
            old_name='shift_begining',
            new_name='shift_beginning',
        ),
    ]
