# Generated by Django 4.2.7 on 2023-12-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0002_rename_shift_begining_shiftmanagement_shift_beginning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmanagement',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
