# Generated by Django 4.2.7 on 2023-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0003_alter_shiftmanagement_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmanagement',
            name='shift_name',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
