# Generated by Django 4.2.7 on 2023-11-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empgrp', '0001_initial'),
        ('device', '0005_device_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empgrp.group')),
            ],
        ),
    ]
