# Generated by Django 4.2.7 on 2023-11-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empgrp', '0001_initial'),
        ('grpdev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdevice',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_group_id', to='empgrp.group'),
        ),
    ]
