# Generated by Django 4.2.7 on 2023-11-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grpdev', '0002_alter_groupdevice_group_id'),
    ]

    operations = [
    ]
