# Generated by Django 4.2.7 on 2023-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(default='-', max_length=100)),
                ('description', models.TextField(default='-', null=True)),
            ],
        ),
    ]
